var demoList = [
  { name: "Simple Print", url: "simple-print.slang" },
  { name: "Simple Image", url: "simple-image.slang" },
  { name: "Load From URL", url: "load-from-url.slang" },
  { name: "-", url: "" },
  { name: "ShaderToy: Circle", url: "circle.slang" },
  { name: "ShaderToy: Ocean", url: "ocean.slang" },
  { name: "2D Splat Rasterizer", url: "gsplat2d.slang" },
  { name: "-", url: "" },
  { name: "Properties", url: "property.slang" },
  { name: "Generics & Extensions", url: "generic.slang" },
  { name: "Operator Overload", url: "operator-overload.slang" },
  { name: "Variadic Generics", url: "variadic.slang" },
  { name: "Automatic Differentiation", url: "autodiff.slang" },
  { name: "Graphics Entrypoints", url: "entrypoint.slang" },
];